server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:microservices}
    username: ${DATABASE_USERNAME:microservices}
    password: ${DATABASE_PASSWORD:secret123}
  flyway:
    schemas: shopping
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: shopping

management:
  endpoints:
    web:
      exposure:
        include: health

application:
  urls:
    user-api: http://${USER_API_HOST:localhost}:${USER_API_PORT:8080}/users/
    product-api: http://${PRODUCT_API_HOST:localhost}:${PRODUCT_API_PORT:8081}/products/