version: "3"

services:

  database:
    image: postgres:14-alpine
    container_name: 'microservices-db'
    ports:
    - 5432:5432
    environment:
      POSTGRES_DB: 'microservices'
      POSTGRES_USER: 'microservices'
      POSTGRES_PASSWORD: 'secret123'