apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
    spec:
      containers:
      - name: user-api
        image: pgjbz/user-api:0.0.1
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: posrgres-configs
              key: host
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: posrgres-configs
              key: database
        - name: DATABASE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: posrgres-configs
              key: username        
        - name: DATABASE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: posrgres-configs
              key: password
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: user-api-services
spec:
  selector:
    app: user-api
  ports:
  - port: 8080
    targetPort: 8080
