apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping-api
  template:
    metadata:
      labels:
        app: shopping-api
    spec:
      containers:
      - name: shopping-api
        image: pgjbz/shopping-api:0.1.0
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: posrgres-configs
              key: host
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: posrgres-configs
              key: database
        - name: DATABASE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: posrgres-configs
              key: username        
        - name: DATABASE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: posrgres-configs
              key: password
        - name: USER_API_HOST
          valueFrom:
            configMapKeyRef:
              name: shopping-config-map
              key: user-api
        - name: USER_API_PORT
          valueFrom:
            configMapKeyRef:
              name: shopping-config-map
              key: user-api-port
        - name: PRODUCT_API_HOST
          valueFrom:
            configMapKeyRef:
              name: shopping-config-map
              key: product-api
        - name: PRODUCT_API_PORT
          valueFrom:
            configMapKeyRef:
              name: shopping-config-map
              key: product-api-port
        ports:
        - containerPort: 8081
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 15
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: shopping-api-services
spec:
  selector:
    app: shopping-api
  type: LoadBalancer
  ports:
  - port: 8082
    targetPort: 8082
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shopping-config-map
data:
  user-api: user-api-services
  user-api-port: '8080'
  product-api: product-api-services
  product-api-port: '8081'
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: shopping-api
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shopping-api
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80